version: '3.4'

services:
  betterdaytool:
    image: betterdaytool
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8080:8080
      - 8081:8081
