version: '3.4'
services:
  your-app:
    environment:
      SPRING_PROFILES_ACTIVE: development
    volumes:
      - ./target:/app
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "betterdaytool.jar"]

